# basic options
title: jagadeeshportfolio
author: jagadeesh
email: kotavenkatajagadeesh5@gmail.com
description: Here are some interesting articles about something i am interested in.
twitter_username: jaga_deesh5555
github_username:  jagadeesh432

# Build settings
markdown: kramdown
theme: minima
